### ISSUE TITLE
meta description

### ISSUE THREAD

**Issue by hnordt** [GoogleChromeLabs/pwacompat#19]
It would be nice to read `description` from the manifest and add it as `<meta name="description" />` if that tag is not already present.

**Comment by samthor** [comment]
I could do this but I'm not sure of the added value. I suspect most sites that are reading this kind of meta from the HTML itself aren't running the page's JS—think e.g., sharing a link on Twitter.

Is there another reason why this might be useful?

**Comment by hnordt** [comment]
The main reason is to avoid this Lighthouse's warning:

![Img](https://d.pr/i/4oER0o+)

https://developers.google.com/web/tools/lighthouse/audits/description

**Comment by samthor** [comment]
I really believe that most crawlers/etc are not going to run page JavaScript just to read your site's meta tags.

So while it might make Lighthouse happy, I suspect this change won't actually improve your SEO.

**Comment by hnordt** [comment]
I understand your point, but I'm not sure it would be a bad thing. You could just check if there is a meta description already and add one based on manifest if not.

Just as `theme_color`, I don't like to have to duplicate it on my HTML head.

**Comment by Malvoz** [comment]
Unlike `<title>` (under some circumstances) a `<meta>` description isn't required in HTML. If you don't need it, should you add it just to appease the Lighthouse tool?

> I really believe that most crawlers/etc are not going to run page JavaScript just to read your site's meta tags.
> 
> So while it might make Lighthouse happy, I suspect this change won't actually improve your SEO.

I haven't googled it but I'm _quite_ sure Google can index script-generated content, however if Google saw the same `<meta>` description across several pages then the site-owner may start worrying about "SEO penalties" due to duplicate content.

Personally I don't think this is a good default for PWACompat.

**Comment by samthor** [comment]
Sorry @hnordt but I also don't think this is worth including.

PWACompat is not intended to help with search indexability. I've had #22 filed and I'll mention this as part of resolving that issue.

**Comment by hnordt** [comment]
Thank you for having a look at it @samthor. I agree with you.
