### ISSUE TITLE
Customize/specify font used on generated splash screen

### ISSUE THREAD

**Issue by 7-of-9** [GoogleChromeLabs/pwacompat#25]
Hi there, 

Nice lib. Is it possible somehow to change the font used on the splash screen that's generated?

Would be a nice addition so that the splash matches whatever font the PWA uses.

**Comment by samthor** [comment]
It could be possible but I'm not really sure where to put the "configuration".I'd be open to suggestions.

**Comment by samthor** [comment]
We're thinking about providing this through CSS variables that we find on the `<link rel="manifest" />` HTML element itself (which can be styled even though this otherwise makes no sense). We could also maybe support customizing the generated colors.

We'd use CSS variables rather than just say, reading `font`, because otherwise we'll use the user-agent font or anything set on `html { ... }`. And these are supported from Safari on iOS 9.3 on onwards (which is supported by iOS devices from iPhone 4s+).

Would that work for you?

**Comment by 7-of-9** [comment]
Yep, that would work!

**Comment by lipis** [comment]
A friendly reminder :)

**Comment by samthor** [comment]
I'll take a look in the next day or so.

**Comment by tomayac** [comment]
> I'm not really sure where to put the "configuration".

Maybe the whole thing could be remodeled as a custom element?

`<pwa-compat foo="bar"></pwa-compat>`

**Comment by samthor** [comment]
I think the zero config model for most people is the best. And it's a
singleton anyway.

**Comment by samthor** [comment]
This is fixed by the v2.0.11 release. You can specify `--pwacompat-splash-font: 24px Verdana` to customize the font, see the readme for some more info.

**Comment by lipis** [comment]
Thanks @samthor!
