### ISSUE TITLE
Build Tool

### ISSUE THREAD

**Issue by pspeter3** [GoogleChromeLabs/pwacompat#9]
Is it possible to run this is as a CLI tool or Webpack plugin instead of at runtime?

**Comment by samthor** [comment]
The old version (v1) used to have a mode where we'd generate icons etc at build time so you could add them to your HTML. But that didn't persist into v2, largely because the code needed for different browsers is very different—and also some features don't make sense, e.g., iOS Safari splash screens must be generated dynamically for the current device's screen size.

I'm not really sure the limited subset of build-time features makes sense (generating `<link rel="icon" ... />` and a couple of others). Maybe that's a different plugin :)

All I will say is that the code could easily be included/required/etc into any pipeline. It would never export anything, it would just have side effects, and it can be loaded `async`.

**Comment by pspeter3** [comment]
That makes sense. Thank you for explaining!

**Comment by firtman** [comment]
You can always generate static images for all possible iOS devices (the list is public and limited) and then assign them client-side through media queries in the link element or just deciding with JavaScript. I don't see a reason to say that you must generate them dynamically client-side. That is just one option, probably the simplest one but also the less customizable.
